// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7yJEbYX7_DNrq0x9T4_4pkXn3i7FPW50',
    appId: '1:106576335129:web:78fcdfa578b307f907b588',
    messagingSenderId: '106576335129',
    projectId: 'mylogs-7b835',
    authDomain: 'mylogs-7b835.firebaseapp.com',
    storageBucket: 'mylogs-7b835.firebasestorage.app',
    measurementId: 'G-C5XB1SQWFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4bCLBPcfBBzEl_NOEemf8z-GF73NdWKg',
    appId: '1:106576335129:android:6044d7e089fec81b07b588',
    messagingSenderId: '106576335129',
    projectId: 'mylogs-7b835',
    storageBucket: 'mylogs-7b835.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnJFxTwFqJO1gDTxkh1xeAPPg5P8sSQHQ',
    appId: '1:106576335129:ios:9d1366c41ef3244407b588',
    messagingSenderId: '106576335129',
    projectId: 'mylogs-7b835',
    storageBucket: 'mylogs-7b835.firebasestorage.app',
    iosBundleId: 'com.example.myLogs',
  );
}
